import {Router} from 'express'; import {z} from 'zod'; import {Content,Rating,Like,Favorite,Status,Review,User} from '../models/index.js'; import {db} from '../db/mongoose.js'; import {auth} from '../middleware/core.js'; import {enrich,recalcRating} from '../services/content.js'; import {activity,notify} from '../services/social.js';
const r=Router(); const id=z.string().regex(/^[a-f0-9]{24}$/i);
r.get('/',auth(false),async(req,res,next)=>{try{await db();const q=z.object({type:z.enum(['MOVIE','BOOK']).optional(),q:z.string().trim().max(100).optional(),genre:z.string().optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(50).default(20),sort:z.enum(['popular','rating','new']).default('popular')}).parse(req.query);const filter={deletedAt:null};if(q.type)filter.type=q.type;if(q.genre)filter.genres=q.genre;if(q.q)filter.$or=[{title:{$regex:q.q,$options:'i'}},{originalTitle:{$regex:q.q,$options:'i'}},{creatorNames:{$regex:q.q,$options:'i'}},{authorNames:{$regex:q.q,$options:'i'}},{isbn:{$regex:q.q,$options:'i'}}];const sort=q.sort==='rating'?{averageRating:-1,ratingCount:-1}:q.sort==='new'?{year:-1,_id:-1}:{popularity:-1,likeCount:-1};const items=await Content.find(filter).sort(sort).skip((q.page-1)*q.limit).limit(q.limit).lean();res.json({items:await Promise.all(items.map(x=>enrich(x,req.user?.sub))),page:q.page,limit:q.limit});}catch(e){next(e)}});
r.get('/:id',auth(false),async(req,res,next)=>{try{await db();const c=await Content.findOne({_id:req.params.id,deletedAt:null}).lean();if(!c)return res.status(404).json({error:'Content not found'});const reviews=await Review.find({contentId:c._id,deletedAt:null}).sort({createdAt:-1}).limit(30).populate('userId','username displayName avatarUrl').lean();res.json({content:await enrich(c,req.user?.sub),reviews});}catch(e){next(e)}});
r.post('/:id/status',auth(),async(req,res,next)=>{try{await db();const c=await Content.findById(req.params.id);if(!c)return res.status(404).json({error:'Content not found'});const allowed=c.type==='MOVIE'?['WATCHED','WATCHLIST']:['WANT_TO_READ','CURRENTLY_READING','READ'];const x=z.object({status:z.string(),progress:z.number().int().min(0).max(100).optional()}).parse(req.body);if(!allowed.includes(x.status))return res.status(400).json({error:'Invalid status for content type'});const s=await Status.findOneAndUpdate({userId:req.user?.sub,contentId:c._id},{$set:{status:x.status,progress:x.progress,completedAt:(x.status==='WATCHED'||x.status==='READ')?new Date():undefined}},{upsert:true,new:true});await activity(req.user?.sub,x.status,c._id);res.json({status:s});}catch(e){next(e)}});
r.post('/:id/rating',auth(),async(req,res,next)=>{try{await db();const c=await Content.findById(req.params.id);if(!c)return res.status(404).json({error:'Content not found'});const x=z.object({score:z.number().min(.5).max(5)}).parse(req.body);const rr=await Rating.findOneAndUpdate({userId:req.user?.sub,contentId:c._id},{$set:{score:x.score}},{upsert:true,new:true});await recalcRating(c._id);await activity(req.user?.sub,'RATED',c._id);res.json({rating:rr});}catch(e){next(e)}});
async function toggle(Model,field,req,res){const c=await Content.findById(req.params.id);if(!c)return res.status(404).json({error:'Content not found'});const found=await Model.findOne({userId:req.user?.sub,contentId:c._id});if(found){await Model.deleteOne({_id:found._id});await Content.updateOne({_id:c._id},{$inc:{[field]:-1}});return res.json({active:false});}await Model.create({userId:req.user?.sub,contentId:c._id});await Content.updateOne({_id:c._id},{$inc:{[field]:1}});await activity(req.user?.sub,field==='likeCount'?'LIKED':'FAVORITED',c._id);res.json({active:true});}
r.post('/:id/like',auth(),(req,res,next)=>toggle(Like,'likeCount',req,res).catch(next));
r.post('/:id/favorite',auth(),(req,res,next)=>toggle(Favorite,'favoriteCount',req,res).catch(next));
r.post('/:id/reviews',auth(),async(req,res,next)=>{try{await db();const c=await Content.findById(req.params.id);if(!c)return res.status(404).json({error:'Content not found'});const x=z.object({body:z.string().min(1).max(10000),spoiler:z.boolean().default(false)}).parse(req.body);const rv=await Review.create({userId:req.user?.sub,contentId:c._id,...x});await activity(req.user?.sub,'REVIEWED',c._id,rv._id);res.status(201).json({review:rv});}catch(e){next(e)}});

r.patch('/:contentId/reviews/:reviewId',auth(),async(req,res,next)=>{try{await db();const x=z.object({body:z.string().min(1).max(10000).optional(),spoiler:z.boolean().optional()}).parse(req.body);const rv=await Review.findOneAndUpdate({_id:req.params.reviewId,contentId:req.params.contentId,userId:req.user?.sub,deletedAt:null},{$set:x},{new:true});if(!rv)return res.status(404).json({error:'Review not found'});res.json({review:rv});}catch(e){next(e)}});
r.delete('/:contentId/reviews/:reviewId',auth(),async(req,res,next)=>{try{await db();const rv=await Review.findOneAndUpdate({_id:req.params.reviewId,contentId:req.params.contentId,userId:req.user?.sub,deletedAt:null},{$set:{deletedAt:new Date()}},{new:true});if(!rv)return res.status(404).json({error:'Review not found'});res.json({deleted:true});}catch(e){next(e)}});
export default r;
