// ── Curated Masterpieces Dataset ──
// High-fidelity photography and editorial critique data for LastPage

export const CURATED_MOVIES = [
  {
    _id: 'm-in-the-mood-for-love',
    type: 'MOVIE',
    title: 'In the Mood for Love',
    year: 2000,
    genres: ['Romance', 'Drama', 'Art House'],
    creatorNames: ['Wong Kar-wai'],
    director: 'Wong Kar-wai',
    runtime: '98 min',
    releaseDate: 'September 29, 2000',
    expertScore: 92,
    communityScore: 4.9,
    ratingBreakdown: { 5: 82, 4: 13, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
    tagline: 'Feel the heat, the fragrance, and the silence of a secret romance.',
    quote: 'He remembers those vanished years. As though looking through a dusty windowpane, the past is something he could see, but not touch.',
    description: 'Two neighbors form a delicate, unspoken bond after discovering their spouses are having an affair. Set against the tight corridors of 1962 British Hong Kong, it is a masterwork of longing, color, and restraint.',
    editorialReview: 'Wong Kar-wai transforms repressed desire into high cinematic art. Christopher Doyle and Mark Lee Ping-bin’s cinematography frames Tony Leung and Maggie Cheung within tight, claustrophobic hallways where every brush of fabric and swirl of cigarette smoke echoes an eternity of unspoken ache. Shigeru Umebayashi’s hypnotic waltz threads together memories of what could have been.',
    reviewer: {
      name: 'Julian Vance',
      role: 'Senior Film Essayist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    },
    averageRating: 4.9,
    ratingCount: 1840,
    likeCount: 1420,
    favoriteCount: 980,
    featured: true,
  },
  {
    _id: 'm-blade-runner-2049',
    type: 'MOVIE',
    title: 'Blade Runner 2049',
    year: 2017,
    genres: ['Sci-Fi', 'Neo-Noir', 'Atmospheric'],
    creatorNames: ['Denis Villeneuve'],
    director: 'Denis Villeneuve',
    runtime: '164 min',
    releaseDate: 'October 6, 2017',
    expertScore: 89,
    communityScore: 4.8,
    ratingBreakdown: { 5: 76, 4: 18, 3: 4, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&q=85',
    tagline: 'The key to the future is finally unearthed.',
    quote: 'All the best memories are hers. Sometimes to love someone, you got to be a stranger.',
    description: 'Officer K uncovers a long-buried secret that has the potential to plunge what is left of society into chaos, leading him to find Rick Deckard in an astonishing vision of future Los Angeles.',
    editorialReview: 'Denis Villeneuve and Roger Deakins accomplish the impossible: expanding Ridley Scott’s seminal cyberpunk universe while crafting a profoundly philosophical meditation on what constitutes the human soul. The apocalyptic orange ruins of Las Vegas and monochromatic downpours of Los Angeles establish one of the most towering visual spectacles in cinematic history.',
    reviewer: {
      name: 'Marcus Thorne',
      role: 'Cinematic Aesthetics Editor',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 2650,
    likeCount: 1980,
    favoriteCount: 1240,
    featured: true,
  },
  {
    _id: 'm-yi-yi',
    type: 'MOVIE',
    title: 'Yi Yi',
    year: 2000,
    genres: ['Drama', 'Family', 'Art House'],
    creatorNames: ['Edward Yang'],
    director: 'Edward Yang',
    runtime: '173 min',
    releaseDate: 'December 16, 2000',
    expertScore: 93,
    communityScore: 4.9,
    ratingBreakdown: { 5: 80, 4: 15, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&q=85',
    tagline: 'A one and a two...',
    quote: 'I want to show people things they can’t see on their own.',
    description: 'A luminous, multi-perspective examination of a modern Taipei family\'s emotional and philosophical lives, seen through the candid lens of childhood and adulthood.',
    editorialReview: 'Edward Yang’s final masterpiece feels less like watching a movie and more like inhabiting life itself. Through little Yang-Yang taking photographs of the backs of people’s heads so they can see what they cannot, Yang gives world cinema an enduring, gentle wisdom on memory, urban solitude, and grace.',
    reviewer: {
      name: 'Clara Lin',
      role: 'Asian Cinema Curator',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80',
    },
    averageRating: 4.9,
    ratingCount: 1150,
    likeCount: 880,
    favoriteCount: 740,
  },
  {
    _id: 'm-stalker',
    type: 'MOVIE',
    title: 'Stalker',
    year: 1979,
    genres: ['Sci-Fi', 'Philosophy', 'Art House'],
    creatorNames: ['Andrei Tarkovsky'],
    director: 'Andrei Tarkovsky',
    runtime: '162 min',
    releaseDate: 'May 1, 1979',
    expertScore: 90,
    communityScore: 4.8,
    ratingBreakdown: { 5: 77, 4: 16, 3: 5, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=1600&q=85',
    tagline: 'In the Zone, the shortest path is never a straight line.',
    quote: 'Let everything that’s been planned come true. Let them believe. And let them have a laugh at their passions.',
    description: 'A guide leads a writer and a scientist through a forbidden mysterious \'Zone\' to a fabled room said to fulfill humanity\'s deepest subconscious desires.',
    editorialReview: 'Tarkovsky sculpts in time, guiding viewers through sepia-drenched industrial decay into a shimmering, lush green wilderness alive with transcendent dread and longing. Stalker remains an unmatched spiritual test of faith, reason, and human fallibility.',
    reviewer: {
      name: 'Julian Vance',
      role: 'Senior Film Essayist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 1120,
    likeCount: 780,
    favoriteCount: 610,
  },
  {
    _id: 'm-paris-texas',
    type: 'MOVIE',
    title: 'Paris, Texas',
    year: 1984,
    genres: ['Drama', 'Road Movie', 'Poetic'],
    creatorNames: ['Wim Wenders'],
    director: 'Wim Wenders',
    runtime: '145 min',
    releaseDate: 'May 19, 1984',
    expertScore: 94,
    communityScore: 4.8,
    ratingBreakdown: { 5: 75, 4: 18, 3: 5, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&q=85',
    tagline: 'A place for dreams. A place for heartbreaks.',
    quote: 'I knew these people... these two people. They were in love with each other. The girl was very young, about sixteen...',
    description: 'A silent wanderer emerges from the scorched Texas desert, attempting to piece back together his shattered identity and reunite with his estranged family.',
    editorialReview: 'Robby Müller’s luminous neon palettes and Ry Cooder’s lonely slide guitar weave an indelible tapestry of the American Southwest. Harry Dean Stanton delivers the performance of a lifetime in this tender, devastating portrait of love lost and forgiveness sought.',
    reviewer: {
      name: 'Marcus Thorne',
      role: 'Cinematic Aesthetics Editor',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 1290,
    likeCount: 940,
    favoriteCount: 710,
  },
  {
    _id: 'm-persona',
    type: 'MOVIE',
    title: 'Persona',
    year: 1966,
    genres: ['Psychological Drama', 'Mystery'],
    creatorNames: ['Ingmar Bergman'],
    director: 'Ingmar Bergman',
    runtime: '85 min',
    releaseDate: 'October 18, 1966',
    expertScore: 96,
    communityScore: 4.7,
    ratingBreakdown: { 5: 73, 4: 20, 3: 5, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&q=85',
    tagline: 'A sonata for two voices.',
    quote: 'The hopeless dream of being. Not seeming to be, but being. Conscious of every tone and mask.',
    description: 'An acclaimed stage actress suddenly falls mute during a performance; her nurse\'s identity slowly, irrevocably fuses with her own in this psychological masterwork.',
    editorialReview: 'Bergman interrogates the fragile illusion of identity and artistic persona with blistering modernism. Sven Nykvist’s high-contrast monochrome cinematography dissects Bibi Andersson and Liv Ullmann’s faces until boundaries collapse into iconic cinema history.',
    reviewer: {
      name: 'Julian Vance',
      role: 'Senior Film Essayist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    },
    averageRating: 4.7,
    ratingCount: 890,
    likeCount: 620,
    favoriteCount: 450,
  },
  {
    _id: 'm-grand-budapest',
    type: 'MOVIE',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genres: ['Comedy', 'Drama', 'Aesthetic'],
    creatorNames: ['Wes Anderson'],
    director: 'Wes Anderson',
    runtime: '99 min',
    releaseDate: 'March 28, 2014',
    expertScore: 88,
    communityScore: 4.7,
    ratingBreakdown: { 5: 72, 4: 21, 3: 5, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1455587734955-081b22074882?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=85',
    tagline: 'A confectionery heist in the heart of Europe.',
    quote: 'There are still faint glimmers of civilization left in this barbaric slaughterhouse that was once known as humanity.',
    description: 'The exploits of legendary concierge M. Gustave and lobby boy Zero Moustafa in a pastel-hued Central European spa town between the great wars.',
    editorialReview: 'A sublime pastry box containing a wistful elegy for a vanishing world. Anderson balances exquisite dollhouse precision with deep melancholia inspired by Stefan Zweig, anchoring the eccentric caper with Ralph Fiennes’ glorious career-best turn.',
    reviewer: {
      name: 'Clara Lin',
      role: 'Asian Cinema Curator',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&q=80',
    },
    averageRating: 4.7,
    ratingCount: 2310,
    likeCount: 1680,
    favoriteCount: 990,
  },
  {
    _id: 'm-drive-my-car',
    type: 'MOVIE',
    title: 'Drive My Car',
    year: 2021,
    genres: ['Drama', 'Meditative'],
    creatorNames: ['Ryusuke Hamaguchi'],
    director: 'Ryusuke Hamaguchi',
    runtime: '179 min',
    releaseDate: 'August 20, 2021',
    expertScore: 91,
    communityScore: 4.7,
    ratingBreakdown: { 5: 71, 4: 21, 3: 6, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1600&q=85',
    tagline: 'We must keep on living.',
    quote: 'Those who survive keep thinking about the dead. In one way or another, that will continue. You and I must keep on living like that.',
    description: 'A widowed theater director is assigned a quiet young driver for his vintage red Saab 900 while staging Chekhov\'s Uncle Vanya in Hiroshima.',
    editorialReview: 'Hamaguchi turns an intimate car cabin into a sacred confessional. As the red Saab cruises quiet coastal highways, dialogue strips away artifice to uncover the raw, shared grief that makes genuine healing possible.',
    reviewer: {
      name: 'Elena Rostova',
      role: 'Comparative Literature Scholar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    },
    averageRating: 4.7,
    ratingCount: 920,
    likeCount: 680,
    favoriteCount: 510,
  },
];

export const CURATED_BOOKS = [
  {
    _id: 'b-ficciones',
    type: 'BOOK',
    title: 'Ficciones',
    year: 1944,
    genres: ['Philosophical Fiction', 'Short Stories', 'Labyrinthine'],
    authorNames: ['Jorge Luis Borges'],
    author: 'Jorge Luis Borges',
    pages: '174 pages',
    releaseDate: 'August 19, 1944',
    expertScore: 98,
    communityScore: 4.9,
    ratingBreakdown: { 5: 84, 4: 12, 3: 3, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1600&q=85',
    tagline: 'The universe (which others call the Library) is composed of an indefinite sphere...',
    quote: 'I have always imagined that Paradise will be a kind of library.',
    description: 'A labyrinth of metaphysical paradoxes, infinite hexagonal libraries, and imaginary encyclopedias that forever revolutionized world literature and philosophy.',
    editorialReview: 'Borges does not merely write stories; he constructs conceptual cathedrals. Within fewer than two hundred pages, Ficciones creates infinite labyrinths, forgotten manuscripts, and alternate cosmoses. It is a work of intellectual sorcery that anticipates hypertexts, virtual realities, and modern existential inquiry.',
    reviewer: {
      name: 'Elena Rostova',
      role: 'Comparative Literature Scholar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    },
    averageRating: 4.9,
    ratingCount: 1420,
    likeCount: 1180,
    favoriteCount: 960,
    featured: true,
  },
  {
    _id: 'b-the-secret-history',
    type: 'BOOK',
    title: 'The Secret History',
    year: 1992,
    genres: ['Psychological Fiction', 'Dark Academia', 'Mystery'],
    authorNames: ['Donna Tartt'],
    author: 'Donna Tartt',
    pages: '559 pages',
    releaseDate: 'September 16, 1992',
    expertScore: 91,
    communityScore: 4.8,
    ratingBreakdown: { 5: 78, 4: 16, 3: 4, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1600&q=85',
    tagline: 'Beauty is terror. Whatever we call beautiful, we quiver before it.',
    quote: 'Does such a thing as "the fatal flaw," that daunting gallows platform, really exist outside of literature?',
    description: 'A cloistered group of eccentric Greek scholars at an elite Vermont college descends irrevocably into obsessive aesthetics, moral detachment, and murder.',
    editorialReview: 'Tartt’s debut redefined literary suspense, giving birth to the Dark Academia ethos. Wrapped in snow-dusted New England ivies and ancient Greek philosophy, Tartt dissects the terrifying seduction of beauty untethered from morality.',
    reviewer: {
      name: 'Julian Vance',
      role: 'Senior Film & Literary Essayist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 2450,
    likeCount: 1890,
    favoriteCount: 1340,
    featured: true,
  },
  {
    _id: 'b-invisible-cities',
    type: 'BOOK',
    title: 'Invisible Cities',
    year: 1972,
    genres: ['Poetic Fiction', 'Philosophy', 'Architecture'],
    authorNames: ['Italo Calvino'],
    author: 'Italo Calvino',
    pages: '165 pages',
    releaseDate: 'November 1, 1972',
    expertScore: 94,
    communityScore: 4.8,
    ratingBreakdown: { 5: 79, 4: 16, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1568454537842-d933259bb258?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=1600&q=85',
    tagline: 'Fifty-five imaginary cities mapped across the mind of an emperor.',
    quote: 'You take delight not in a city’s seven or seventy wonders, but in the answer it gives to a question of yours.',
    description: 'Marco Polo recounts dazzling, impossible descriptions of fifty-five imaginary cities to aging Mongol emperor Kublai Khan.',
    editorialReview: 'Calvino transforms urban topography into pure poetic music. Each miniature city—built on stilts, suspended over voids, or woven from spiderwebs of memory—is a prism through which human longing, architecture, and semiotics shine with diamond clarity.',
    reviewer: {
      name: 'Elena Rostova',
      role: 'Comparative Literature Scholar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 1250,
    likeCount: 980,
    favoriteCount: 810,
  },
  {
    _id: 'b-dune',
    type: 'BOOK',
    title: 'Dune',
    year: 1965,
    genres: ['Science Fiction', 'Epic', 'Ecology'],
    authorNames: ['Frank Herbert'],
    author: 'Frank Herbert',
    pages: '688 pages',
    releaseDate: 'August 1, 1965',
    expertScore: 93,
    communityScore: 4.8,
    ratingBreakdown: { 5: 77, 4: 17, 3: 4, 2: 1, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1600&q=85',
    tagline: 'A beginning is the time for taking the most delicate care...',
    quote: 'I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.',
    description: 'Feudal geopolitics, messianic destiny, and ecology collide on the unforgiving desert planet of Arrakis.',
    editorialReview: 'Herbert crafted the definitive literary monument of world-building. Dune is far more than a space opera—it is an intricate study of planetary ecology, the weaponization of religion, and the perilous nature of charismatic leaders.',
    reviewer: {
      name: 'Marcus Thorne',
      role: 'Speculative Fiction Analyst',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 3100,
    likeCount: 2400,
    favoriteCount: 1650,
  },
  {
    _id: 'b-the-master-and-margarita',
    type: 'BOOK',
    title: 'The Master and Margarita',
    year: 1967,
    genres: ['Satire', 'Magic Realism', 'Russian Classic'],
    authorNames: ['Mikhail Bulgakov'],
    author: 'Mikhail Bulgakov',
    pages: '412 pages',
    releaseDate: 'May 1, 1967',
    expertScore: 95,
    communityScore: 4.8,
    ratingBreakdown: { 5: 80, 4: 15, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1538681105587-85640961bf8b?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
    tagline: 'Manuscripts don\'t burn.',
    quote: 'Follow me, reader! Who told you that there is no true, faithful, eternal love in this world?',
    description: 'Satan arrives in atheistic 1930s Moscow accompanied by an entourage including a talking black cat, upending Soviet bureaucracy with magical mayhem.',
    editorialReview: 'Written in secret under Stalin’s terror, Bulgakov’s masterpiece is a soaring defiant carnival of imagination. Intertwining Pontius Pilate’s guilt in ancient Yershalaim with devils exposing Soviet greed, it stands as proof that art outlives tyrants.',
    reviewer: {
      name: 'Elena Rostova',
      role: 'Comparative Literature Scholar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 1140,
    likeCount: 890,
    favoriteCount: 710,
  },
  {
    _id: 'b-norwegian-wood',
    type: 'BOOK',
    title: 'Norwegian Wood',
    year: 1987,
    genres: ['Literary Fiction', 'Memory', 'Tokyo'],
    authorNames: ['Haruki Murakami'],
    author: 'Haruki Murakami',
    pages: '296 pages',
    releaseDate: 'September 4, 1987',
    expertScore: 88,
    communityScore: 4.6,
    ratingBreakdown: { 5: 68, 4: 22, 3: 7, 2: 2, 1: 1 },
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1600&q=85',
    tagline: 'Death is not the opposite of life, but a part of it.',
    quote: 'If you only read the books that everyone else is reading, you can only think what everyone else is thinking.',
    description: 'A Beatles song heard at a German airport sends Toru Watanabe tumbling into memories of college in late-1960s Tokyo and his first tragic love.',
    editorialReview: 'Murakami sets aside his customary talking cats and magical wells for an achingly nostalgic, acoustic chronicle of youth, grief, and budding sexuality amidst autumn rain and quiet jazz bars.',
    reviewer: {
      name: 'Julian Vance',
      role: 'Senior Film & Literary Essayist',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    },
    averageRating: 4.6,
    ratingCount: 1920,
    likeCount: 1350,
    favoriteCount: 920,
  },
  {
    _id: 'b-the-remains-of-the-day',
    type: 'BOOK',
    title: 'The Remains of the Day',
    year: 1989,
    genres: ['Literary Fiction', 'English Period', 'Nobel'],
    authorNames: ['Kazuo Ishiguro'],
    author: 'Kazuo Ishiguro',
    pages: '258 pages',
    releaseDate: 'May 18, 1989',
    expertScore: 96,
    communityScore: 4.8,
    ratingBreakdown: { 5: 79, 4: 16, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&q=85',
    tagline: 'A journey across England. A reckoning with a wasted life.',
    quote: 'Indeed — why should I not admit it? — at that moment, my heart was breaking.',
    description: 'Stevens, a consummate English butler, embarks on a motoring trip across the countryside, slowly revealing the tragic cost of unquestioning deference.',
    editorialReview: 'Nobel laureate Ishiguro crafts one of the greatest unreliable narrators in English letters. Stevens’ impeccable, polite prose becomes a veil that slowly slips, revealing an ocean of suppressed heartbreak and moral blindness with devastating quietude.',
    reviewer: {
      name: 'Elena Rostova',
      role: 'Comparative Literature Scholar',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 1080,
    likeCount: 840,
    favoriteCount: 670,
  },
  {
    _id: 'b-the-dispossessed',
    type: 'BOOK',
    title: 'The Dispossessed',
    year: 1974,
    genres: ['Science Fiction', 'Utopian Theory', 'Philosophy'],
    authorNames: ['Ursula K. Le Guin'],
    author: 'Ursula K. Le Guin',
    pages: '387 pages',
    releaseDate: 'May 1, 1974',
    expertScore: 94,
    communityScore: 4.8,
    ratingBreakdown: { 5: 78, 4: 17, 3: 4, 2: 1, 1: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&q=85',
    tagline: 'An ambiguous utopia.',
    quote: 'You cannot buy the revolution. You cannot make the revolution. You can only be the revolution.',
    description: 'A physicist from an arid anarchist moon journeys to its opulent capitalist sister world to finish his revolutionary unified field theory.',
    editorialReview: 'Le Guin’s political imagination is unparalleled. By treating neither society as a sterile fantasy, she explores the grueling labor of human freedom, mutual aid, and the walls we build in our minds.',
    reviewer: {
      name: 'Marcus Thorne',
      role: 'Speculative Fiction Analyst',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    },
    averageRating: 4.8,
    ratingCount: 940,
    likeCount: 730,
    favoriteCount: 590,
  },
];

export function getCuratedItems(type) {
  return type === 'MOVIE' ? CURATED_MOVIES : CURATED_BOOKS;
}

export function getAllCuratedItems() {
  return [...CURATED_MOVIES, ...CURATED_BOOKS];
}
